export const enhancedPostTypes = [
  {
    id: 'howTo', value: 'howTo', label: 'Educational/How-To', category: 'Educational Content',
    description: 'Guides readers through a process or technique.',
    exampleSnippet: 'Learn the 5 steps to master...',
    useCases: ['Skill development', 'Process explanation'],
    performanceIndicator: 'high', isTrending: true,
  },
  {
    id: 'list', value: 'list', label: 'Listicle/Tips', category: 'Educational Content',
    description: 'Presents multiple points or examples in a structured format.',
    exampleSnippet: 'Top 7 tools for...',
    useCases: ['Resource sharing', 'Quick takeaways'],
    performanceIndicator: 'high',
  },
  {
    id: 'toolReview', value: 'toolReview', label: 'Tool/Resource Review', category: 'Educational Content',
    description: 'Evaluates a specific tool or resource.',
    exampleSnippet: 'Is [Tool Name] worth it? My honest review.',
    useCases: ['Product recommendations', 'Software comparisons'],
    performanceIndicator: 'medium',
  },
  {
    id: 'processFramework', value: 'processFramework', label: 'Process/Framework', category: 'Educational Content',
    description: 'Outlines a systematic approach or conceptual model.',
    exampleSnippet: 'The A-B-C framework for...',
    useCases: ['Strategic planning', 'Methodology sharing'],
    performanceIndicator: 'medium',
  },
  {
    id: 'caseStudy', value: 'caseStudy', label: 'Case Study/Results', category: 'Data-Driven Content',
    description: 'Showcases real-world examples and demonstrated results.',
    exampleSnippet: 'How we helped Client X achieve...',
    useCases: ['Proof of concept', 'Success stories'],
    performanceIndicator: 'high',
  },
  {
    id: 'trendAnalysis', value: 'trendAnalysis', label: 'Trend Analysis', category: 'Data-Driven Content',
    description: 'Examines current market movements and future predictions.',
    exampleSnippet: 'The rise of AI in...',
    useCases: ['Market forecasting', 'Industry outlook'],
    performanceIndicator: 'medium',
  },
  {
    id: 'industryInsights', value: 'industryInsights', label: 'Industry Insights', category: 'Data-Driven Content',
    description: 'Provides expert commentary on sector-specific developments.',
    exampleSnippet: 'What the latest report means for...',
    useCases: ['Thought leadership', 'Expert opinion'],
    performanceIndicator: 'medium',
  },
  {
    id: 'comparison', value: 'comparison', label: 'Comparison/Vs Post', category: 'Data-Driven Content',
    description: 'Compares two or more concepts, tools, or strategies.',
    exampleSnippet: 'ChatGPT vs Bard: Which is better for...',
    useCases: ['Decision making', 'Feature comparison'],
    performanceIndicator: 'medium',
  },
  {
    id: 'question', value: 'question', label: 'Question/Poll', category: 'Engagement Content',
    description: 'Engages the audience by asking a direct question or running a poll.',
    exampleSnippet: 'What are your biggest challenges with...? #poll',
    useCases: ['Audience research', 'Community building'],
    performanceIndicator: 'experimental', isTrending: true,
  },
  {
    id: 'personalStory', value: 'personalStory', label: 'Personal Story/Experience', category: 'Engagement Content',
    description: 'Shares authentic experiences to build trust and connection.',
    exampleSnippet: 'This mistake cost me $10k but taught me...',
    useCases: ['Building credibility', 'Humanizing your brand'],
    performanceIndicator: 'high', isTrending: true,
  },
  {
    id: 'contrarian', value: 'contrarian', label: 'Controversial Take/Opinion', category: 'Engagement Content',
    description: 'Challenges conventional thinking to spark debate and engagement.',
    exampleSnippet: 'Unpopular opinion: Why remote work is failing...',
    useCases: ['Generating discussion', 'Standing out'],
    performanceIndicator: 'medium',
  },
  {
    id: 'behindScenes', value: 'behindScenes', label: 'Behind-the-Scenes', category: 'Engagement Content',
    description: 'Offers a glimpse into your work process, team, or company culture.',
    exampleSnippet: 'A day in the life of our AI team...',
    useCases: ['Transparency', 'Employer branding'],
    performanceIndicator: 'experimental',
  },
  {
    id: 'mythBusting', value: 'mythBusting', label: 'Myth-Busting/Fact-Check', category: 'Authority Content',
    description: 'Debunks common misconceptions or verifies facts.',
    exampleSnippet: 'The biggest AI myth you still believe...',
    useCases: ['Educating audience', 'Correcting misinformation'],
    performanceIndicator: 'medium',
  },
  {
    id: 'prediction', value: 'prediction', label: 'Prediction/Future Outlook', category: 'Authority Content',
    description: 'Shares informed predictions about future developments.',
    exampleSnippet: 'My 3 bold predictions for 2024...',
    useCases: ['Thought leadership', 'Foresight'],
    performanceIndicator: 'medium',
  },
  {
    id: 'motivational', value: 'motivational', label: 'Motivational/Inspirational', category: 'Authority Content',
    description: "Inspires and encourages the audience with uplifting messages.",
    exampleSnippet: "Don't give up on your entrepreneurial journey...",
    useCases: ['Community support', 'Personal growth'],
    performanceIndicator: 'medium',
  },
];

export const enhancedHookPatterns = [
  {
    id: 'curiosityGap', value: 'curiosityGap', label: 'Curiosity Gap', category: 'Intrigue & Discovery',
    description: 'Creates intrigue and prompts questions, making readers want to discover the answer.',
    exampleSnippet: "You won't believe what happened next...",
    useCases: ['Generating clicks', 'Building suspense'],
    performanceIndicator: 'high', isTrending: true,
  },
  {
    id: 'pas', value: 'pas', label: 'Problem-Agitate-Solve', category: 'Pain & Solution',
    description: 'Addresses a clear pain point, agitates it, then provides a solution.',
    exampleSnippet: "Struggling with X? Here's how to fix it.",
    useCases: ['Selling solutions', 'Addressing common issues'],
    performanceIndicator: 'high',
  },
  {
    id: 'socialProof', value: 'socialProof', label: 'Social Proof', category: 'Credibility & Trust',
    description: 'Uses evidence, data, or examples to validate a point through external credibility.',
    exampleSnippet: 'Join 10,000+ others who...',
    useCases: ['Building trust', 'Leveraging testimonials'],
    performanceIndicator: 'medium',
  },
  {
    id: 'contrarian', value: 'contrarian', label: 'Contrarian', category: 'Challenge & Debate',
    description: 'Challenges common beliefs or practices, creating interest through new perspectives.',
    exampleSnippet: "Everyone says X, but here's why they're wrong.",
    useCases: ['Sparking discussion', 'Standing out'],
    performanceIndicator: 'medium',
  },
  {
    id: 'authority', value: 'authority', label: 'Authority/Insight', category: 'Expertise & Value',
    description: 'Positions you as an expert voice on the topic, building trust with your audience.',
    exampleSnippet: "As a 10-year veteran in X, I've learned...",
    useCases: ['Establishing leadership', 'Sharing deep knowledge'],
    performanceIndicator: 'high',
  },
  {
    id: 'educational', value: 'educational', label: 'Educational/Framework', category: 'Learning & Guidance',
    description: 'Aligns with structured learning and applicable knowledge, often presenting a framework.',
    exampleSnippet: "Here's the simple framework I use for...",
    useCases: ['Teaching concepts', 'Providing actionable steps'],
    performanceIndicator: 'high',
  },
];

export const enhancedContentPillars = [
  {
    id: 'Technology', value: 'Technology', label: 'Technology', category: 'Core Business',
    description: 'Focuses on technical concepts, digital tools, or technology implementation.',
    exampleSnippet: 'The latest in AI ethics...',
    useCases: ['Tech updates', 'Software reviews'],
    performanceIndicator: 'high', isTrending: true,
  },
  {
    id: 'Leadership', value: 'Leadership', label: 'Leadership', category: 'Core Business',
    description: 'Aligns with management principles, team dynamics, or strategic direction.',
    exampleSnippet: 'Effective leadership in a remote world.',
    useCases: ['Management tips', 'Team building'],
    performanceIndicator: 'high',
  },
  {
    id: 'Human Resource', value: 'Human Resource', label: 'Human Resource', category: 'Core Business',
    description: 'Addresses talent management, workforce issues, or employee experience.',
    exampleSnippet: 'Boosting employee engagement in 2024.',
    useCases: ['HR best practices', 'Recruitment strategies'],
    performanceIndicator: 'medium',
  },
  {
    id: 'Industry Trends', value: 'Industry Trends', label: 'Industry Trends', category: 'Market & Future',
    description: "Examines market movements, future predictions, or sector-wide developments.",
    exampleSnippet: "What's next for digital transformation?",
    useCases: ['Market analysis', 'Future forecasting'],
    performanceIndicator: 'high', isTrending: true,
  },
  {
    id: 'Health Tips', value: 'Health Tips', label: 'Health Tips', category: 'Personal Wellbeing',
    description: 'Matches topics related to wellbeing, medical insights, or healthcare concerns.',
    exampleSnippet: '3 simple habits for better mental health.',
    useCases: ['Wellness advice', 'Preventative care'],
    performanceIndicator: 'medium',
  },
  {
    id: 'Case Studies', value: 'Case Studies', label: 'Case Studies', category: 'Proof & Results',
    description: 'Dedicated pillar for sharing detailed success stories and project outcomes.',
    exampleSnippet: 'Our client saved $X with this strategy.',
    useCases: ['Demonstrating ROI', 'Client success'],
    performanceIndicator: 'high',
  },
];

export const enhancedToneOptions = [
  {
    id: "casual-witty", value: "casual-witty", label: "Casual & Witty", category: 'Informal & Engaging',
    description: "Punchy, first-person riffs with short, staccato sentences, playful sarcasm, and quick take-home lines that feel like a high-engagement LinkedIn scroll.",
    exampleSnippet: "Nobody actually cares about your content strategy. That's what a marketing guru told me last week.",
    useCases: ["Engagement-focused posts", "Counter-intuitive insights", "Personal observations"],
    performanceIndicator: 'high', isTrending: true,
  },
  {
    id: "professional-authority", value: "professional-authority", label: "Professional Authority", category: 'Formal & Expert',
    description: "Balanced, expert voice with clear insights and factual support. Industry leadership with measured confidence.",
    exampleSnippet: "Our latest research indicates...",
    useCases: ["Academic topics", "Industry reports"],
    performanceIndicator: 'high',
  },
  {
    id: "approachable-expert", value: "approachable-expert", label: "Approachable Expert", category: 'Formal & Expert',
    description: "Friendly, accessible expertise. Complex ideas explained simply with relatable examples and occasional humor.",
    exampleSnippet: "Let's break down this complex topic...",
    useCases: ["Educational content", "Beginner guides"],
    performanceIndicator: 'high', isTrending: true,
  },
  {
    id: "snap-snark", value: "snap-snark", label: "Snap & Snark", category: 'Informal & Engaging',
    description: "Punchy, first-person quips. Short, snappy lines. Light sarcasm. Fast takeaways that read like a high-engagement LinkedIn feed.",
    exampleSnippet: "Unpopular opinion: Meetings are dead.",
    useCases: ["Opinion pieces", "Quick takes"],
    performanceIndicator: 'medium',
  },
  {
    id: "plain-talk-playbook", value: "plain-talk-playbook", label: "Plain-Talk Playbook", category: 'Informal & Engaging',
    description: "No fluff. Plain language that turns big ideas into step-by-step moves, with sticky analogies and habit-friendly rules of thumb.",
    exampleSnippet: "Here's the simple truth about...",
    useCases: ["How-to guides", "Actionable advice"],
    performanceIndicator: 'high',
  },
  {
    id: "anecdote-to-aha", value: "anecdote-to-aha", label: "Anecdote to Aha", category: 'Storytelling',
    description: "Start with a scene. Tease a question. Land an unexpected aha—backed by research and smart counterpoints.",
    exampleSnippet: "I almost quit until I realized...",
    useCases: ["Personal growth stories", "Lessons learned"],
    performanceIndicator: 'high', isTrending: true,
  },
  {
    id: "bias-buster", value: "bias-buster", label: "Bias Buster", category: 'Storytelling',
    description: "Wry, rule-bending takes that expose our quirky decision-making and flip conventional wisdom upside down.",
    exampleSnippet: "Your brain is tricking you into...",
    useCases: ["Challenging norms", "Psychology insights"],
    performanceIndicator: 'medium',
  },
  {
    id: "open-heart-honest", value: "open-heart-honest", label: "Open-Heart Honest", category: 'Emotional & Relatable',
    description: "Warm first-person honesty, blending personal moments with evidence-based takeaways to create genuine connection.",
    exampleSnippet: "It's okay to feel overwhelmed, I've been there.",
    useCases: ["Vulnerability", "Empathy building"],
    performanceIndicator: 'medium',
  },
  {
    id: "future-forward-glow", value: "future-forward-glow", label: "Future-Forward Glow", category: 'Visionary',
    description: "Future-forward energy: market maps, sci-fi analogies, and confident bets that paint a hope-filled picture of what's next.",
    exampleSnippet: "Imagine a world where AI...",
    useCases: ["Futurism", "Innovation"],
    performanceIndicator: 'medium',
  },
  {
    id: "money-with-meaning", value: "money-with-meaning", label: "Money With Meaning", category: 'Niche & Specific',
    description: "Calm, reflective essays weaving history, psychology, and money lessons into relatable snapshots with a literary touch.",
    exampleSnippet: "The philosophy of wealth beyond riches.",
    useCases: ["Financial literacy", "Ethical investing"],
    performanceIndicator: 'experimental',
  },
  {
    id: "conversion-mode", value: "conversion-mode", label: "Conversion Mode", category: 'Niche & Specific',
    description: "Benefits first. Pain → solution → proof → CTA. Tight, urgent copy built to convert.",
    exampleSnippet: "Unlock your potential with...",
    useCases: ["Sales copy", "Landing pages"],
    performanceIndicator: 'medium',
  },
  {
    id: "nerdy-fun-run", value: "nerdy-fun-run", label: "Nerdy Fun Run", category: 'Niche & Specific',
    description: "Long-form with stick-figure humor, casual asides, and simple visuals to crack complex ideas—meme-ready and approachable.",
    exampleSnippet: "Let's get nerdy about quantum computing!",
    useCases: ["Complex explanations", "Engaging education"],
    performanceIndicator: 'experimental',
  },
  {
    id: "mission-voice", value: "mission-voice", label: "Mission Voice", category: 'Niche & Specific',
    description: "Purpose-first language that asks the big why, rallies the group, and closes with a clear, uplifting call to act.",
    exampleSnippet: "Join us in building a better future for...",
    useCases: ["Advocacy", "Community rallying"],
    performanceIndicator: 'medium',
  },
];